version: '3.3'
services:
  loopback-server:
    cap_add:
      - ALL
    privileged: true
    command: nodemon --config nodemon.json src/example/loopback-server/index.js
    env_file: .env
    build:
      context: .
      cache_from:
        - node:8.10-alpine
    volumes:
      - .:/app
    ports:
      - '3201:3201'
  client:
    cap_add:
      - ALL
    privileged: true
    command: mocha src/example/client/tests/*
    environment:
      - PAYLOAD_SIZE=5000
      - UP_RATE_KBPS=100
      - DOWN_RATE_KBPS=100
      - ROUND_TRIP_TIME=1
    env_file: .env
    build:
      context: .
      cache_from:
        - node:8.10-alpine
    volumes:
      - .:/app
    links:
      - loopback-server
