version: '3.3'
services:
  vehicle-server:
    command: nodemon --config nodemon.json src/server/index.js
    env_file: .env
    build:
      context: .
      cache_from:
        - node:8.10-alpine
    volumes:
      - .:/app
    ports:
      - '3201:3201'
  vehicle:
    command: nodemon --config nodemon.json src/vehicle/index.js
    env_file: .env
    build:
      context: .
      cache_from:
        - node:8.10-alpine
    volumes:
      - .:/app
    links:
      - vehicle-server
