version: '3.3'
services:
  vehicle-server:
    cap_add:
      - ALL
    privileged: true
    command: nodemon --config nodemon.json src/server/index.js
    env_file: .env
    build:
      context: .
      cache_from:
        - node:8.10-alpine
    volumes:
      - .:/app
    ports:
      - '3201:3201'
  vehicle:
    cap_add:
      - ALL
    privileged: true
    command: nodemon --config nodemon.json src/vehicle/index.js
    environment:
      - PAYLOAD_SIZE=5000
      - UP_RATE_KBPS=50000
      - DOWN_RATE_KBPS=50
      - ROUND_TRIP_TIME=10
    env_file: .env
    build:
      context: .
      cache_from:
        - node:8.10-alpine
    volumes:
      - .:/app
    links:
      - vehicle-server
